@startuml Diagrama_de_subestados

hide empty description

' Estado inicial
state decision <<choice>>
[*] --> decision
decision --> Registrando : Registrar Usuario
state Registrando {
    [*] --> CompletarDatos : Completar datos
    CompletarDatos --> VerificarCorreo : Verificar correo electrónico
    VerificarCorreo --> Confirmado : Confirmar cuenta
}

' Subestados del Usuario

decision --> IniciandoSesion : Iniciar Sesión
state IniciandoSesion {

    UsuarioInactivo --> UsuarioActivo : Activar cuenta
    UsuarioActivo --> UsuarioSuspendido : Cuenta suspendida por violación de reglas
    UsuarioSuspendido --> UsuarioActivo : Reactivar cuenta
    UsuarioActivo --> Sesión_Iniciada : Iniciar sesión
    Sesión_Iniciada --> UsuarioActivo : Cerrar Sesión
}

' Estado inicial del Evento
IniciandoSesion --> publicandoEvento : Publicar evento

' Subestados del Evento
state publicandoEvento {
    [*] --> CreacionEvento : Crear evento
    state RevisandoEvento{
        [*] --> RevisionEvento
RevisionEvento --> AprobandoEvento  
RevisionEvento --> RechazandoEvento  
    }
    state EventoBorrador <<choice>>
    state decision2 <<choice>>
    CreacionEvento --> EventoBorrador : Guardar como borrador
    EventoBorrador --> RevisandoEvento : Publicar evento
    AprobandoEvento --> EventoPublicado : Aprobar evento
    EventoBorrador --> EventoCancelado : Cancelar evento
    EventoCancelado --> [*]
    EventoModificado --> [*]
    EventoPublicado --> decision2
    decision2 --> EventoModificado: Modificar Evento               
    decision2 --> [*]               


}

' Estado inicial del Comentario
IniciandoSesion --> RealizandoComentario : Proceso del Comentario

' Subestados del Comentario
state RealizandoComentario {
    [*] --> CreacionComentario : Crear comentario
    CreacionComentario --> ComentarioPublicado : Publicar comentario
    ComentarioPublicado --> ComentarioEliminado : Eliminar comentario
    ComentarioPublicado --> [*]
    ComentarioEliminado --> [*]
}

' Estado inicial de las Notificaciones
IniciandoSesion --> GenerandoNotificacion : Proceso de las Notificaciones
'Estado Haciendo Publicación
IniciandoSesion --> HaciendoPublicacion: Hacer Publicación
state HaciendoPublicacion{
     [*] --> CreandoPublicacion : Crear Publicación
    CreandoPublicacion --> RevisandoPublicacion : Verificar Publicación
    state RevisandoPublicacion{
state RevisionPublicacion <<choice>>
[*] --> RevisionPublicacion
RevisionPublicacion --> AprobandoPublicacion  
RevisionPublicacion --> RechazandoPublicacion  
    }

    AprobandoPublicacion --> PublicacionCreada : Aprobar Publicación
   state decision3 <<choice>>
   
    CreandoPublicacion --> PublicacionCancelada : Cancelar Publicación
    PublicacionCancelada --> [*]
    PublicacionCreada --> decision3
    decision3 --> PublicacionModificada: Modificar Publicación
    decision3 --> [*]

    PublicacionModificada --> [*]
   
}
' Subestados de las Notificaciones
state GenerandoNotificacion {
    [*] --> CreacionNotificacion : Crear notificación
    CreacionNotificacion --> NotificacionEnviada : Enviar notificación
    NotificacionEnviada --> EstadoNotificacion : Estado de notificación
    state EstadoNotificacion <<choice>> {
        [*] --> Leida : Marcar como leída
        [*] --> Borrada : Borrar
        Leida --> Borrada
        Borrada --> [*]
    }
}
state CerrandoSesion 
HaciendoPublicacion --> CerrandoSesion
GenerandoNotificacion --> CerrandoSesion
Registrando --> CerrandoSesion
IniciandoSesion --> CerrandoSesion
RealizandoComentario --> CerrandoSesion
publicandoEvento --> CerrandoSesion
@enduml

