
@startuml UC3 Publicar evento Traza

left to right direction

Actor "Usuario" as u
Actor "Usuario" as user
package "DisenioVista"{
agent FormularioDeEventos as DFE

}

package "DisenioBack"{
    agent GestorDeEventos as DGE
    agent  "Evento" as devent 
    agent "Calendario" as dcal
    DGE -- devent
    DGE -- dcal
    DFE -- DGE
}

package Analisis{

Actor "Usuario" as u

boundary "FormularioDeEventos" as form
control "GestorDeEventos" as gestor

entity "Evento" as event 
entity "Calendario" as c

  u-- form
form -- gestor 
gestor -- event
gestor -- c
}

user -- DFE
form ....> DFE: traza
gestor ....> DGE: traza
event ....> devent: traza
c ....> dcal: traza

@enduml