
@startuml UC3 Publicar evento Traza

left to right direction

Actor ":Usuario" as u

boundary "FormularioDeEventos" as form
control "GestorDeEventos" as gestor

entity "Evento" as event 
entity "Calendario" as c

  u-- form
form -- gestor 
gestor -- event
gestor -- c


@enduml