@startuml hola

[*]  --> Registrado : Registrarse
Registrado --> SesionIniciada: Iniciar Sesion
[*] --> SesionIniciada
state c1 <<choice>>
SesionIniciada --> c1 : Crear evento
c1 --> Publicado: Publicar evento
c1 --> Descartado: Descartar evento
Publicado --> Modificado: Modificar evento
Publicado --> Eliminado: Eliminar evento

SesionIniciada --> ViendoPublicacion: Ver publicacion
ViendoPublicacion --> ComentarioRealizado: Comentar publicacion
SesionIniciada --> RevisandoCalendario: Revisar calendario 
RevisandoCalendario --> EventoAñadido: Añadir evento
SesionIniciada --> PerfilEditado: Editar perfil
SesionIniciada --> SesionCerrada: Cerrar sesión

Modificado -->  SesionCerrada : Cerrar Sesion
Eliminado -->  SesionCerrada : Cerrar Sesion
Descartado -->  SesionCerrada : Cerrar Sesion
PerfilEditado -->  SesionCerrada : Cerrar Sesion
RevisandoCalendario -->  SesionCerrada : Cerrar Sesion
ComentarioRealizado -->  SesionCerrada : Cerrar Sesion
EventoAñadido --> SesionCerrada : Cerrar Sesion
 SesionCerrada --> [*]


@enduml
