
@startuml UC17 Aprobar Evento o Publicación

left to right direction

Actor ":Moderador" as moderador
control ":GestorDeRevision" as gestor
entity ":Publicacion" as p
entity ":Evento" as e
boundary ":VistaDeEvento" as VistE
boundary ":VistaDePublicacion" as VistaP



gestor -- p  
gestor -- e  
VistE -- gestor
VistaP --gestor 
moderador -- VistE 
moderador -- VistaP 

@enduml